---
apiVersion: v1
kind: Service
metadata:
  name: {{app.name}}
  labels:
    app: {{app.name}}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: {{kubevars.app.cport}}
      port: {{kubevars.app.port}}     
  selector:
    app: {{app.name}}
