---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{app.name}}
  labels:
    app: {{app.name}}
spec:
  selector:
    matchLabels:
      app: {{app.name}}
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: {{app.name}}
    spec:
      securityContext:
        fsGroup: 2537

      containers:
        - image: {{kubevars.app.container_image}}
          imagePullPolicy: Always
          name: {{app.name}}


          volumeMounts:
          - name: ifcs-log-storage
            mountPath: /data
    
          env:
 #           - name: SPRING_PROFILES_ACTIVE
 #             valueFrom:
 #               configMapKeyRef:
 #                 name: petclinic-mysql-configmap
 #                 key: db_profile

            - name: IFCS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ifcs-secret
                  key: IFCS_DB_PASSWORD

            - name: IFCS_REMOTE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ifcs-secret
                  key: IFCS_REMOTE_PASSWORD

            - name: QUARTZ_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ifcs-secret
                  key: QUARTZ_DB_PASSWORD

            - name: IFCS_DB_CONNECTION_URL
              valueFrom:
                configMapKeyRef:
                  name: ifcs-configmap
                  key: IFCS_DB_CONNECTION_URL

            - name: IFCS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ifcs-configmap
                  key: IFCS_DB_USER

            - name: IFCS_DB_MAX_POOL
              valueFrom:
                configMapKeyRef:
                  name: ifcs-configmap
                  key: IFCS_DB_MAX_POOL

            - name: IFCS_DB_MAX_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: ifcs-configmap
                  key: IFCS_DB_MAX_POOL_SIZE


            - name: IFCS_LOG_FILES_PATH
              valueFrom:
                configMapKeyRef:
                  name: ifcs-configmap
                  key: IFCS_LOG_FILES_PATH

            - name: QUARTZ_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ifcs-configmap
                  key: QUARTZ_DB_USER

            - name: POD_NAME
              value: "ifcs"

  
      imagePullSecrets:
       - name: jfrog-secret

      volumes:
      - name: ifcs-log-storage
        persistentVolumeClaim:
          claimName: efs-storage-claim-{{env_name}}

