---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-{{env_name}}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-eb70d1b0::fsap-08ed4834651ecdc83

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-storage-claim-{{env_name}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 3Gi
