---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{app.name}}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTP": 8080}]'
    alb.ingress.kubernetes.io/subnets: subnet-0a8af8cb501c9bced, subnet-01d41c741082b948c 
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: {{app.name}}
              servicePort: 80
